name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Test
      run: cargo test --release
    - name: Build
      run: cargo deb -o ./lyrs_${GITHUB_REF##*/}_amd64.deb --verbose 
    - name: Upload .deb package
      run: |
        ./.github/workflows/upload_asset.sh \
          "alt-art/lyrs" ./lyrs_${GITHUB_REF##*/}_amd64.deb $GITHUB_TOKEN

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/lyrs.exe ./lyrs-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            "alt-art/lyrs" ./lyrs-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN